#name: CI/CD Pipeline
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:15
#        env:
#          POSTGRES_USER: ifiauser
#          POSTGRES_PASSWORD: password
#          POSTGRES_DB: ifiasoft
#        ports:
#          - 5432:5432
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.11'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Run tests
#      env:
#        DATABASE_URL: postgresql+psycopg2://ifiauser:password@localhost:5432/ifiasoft
#        SECRET_KEY: test-secret-key
#        DEBUG: True
#      run: |
#        pytest
#
#    - name: Run linting
#      run: |
#        black . --check
#        ruff check .
#
#  deploy:
#    needs: test
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Deploy to production
#      env:
#        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
#      run: |
#        # Add your deployment steps here
#        # For example, using SSH to deploy to your server
#        echo "Deploying to production..."